var d;d||=typeof Module != 'undefined' ? Module : {};var k="object"==typeof window,l="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q=Object.assign({},d),r=(a,c)=>{throw c;},t="",u,v,w;
if(n){var fs=require("fs"),x=require("path");t=__dirname+"/";u=(a,c)=>{a=B(a)?new URL(a):x.normalize(a);return fs.readFileSync(a,c?void 0:"utf8")};w=a=>{a=u(a,!0);a.buffer||(a=new Uint8Array(a));return a};v=(a,c,b,f=!0)=>{a=B(a)?new URL(a):x.normalize(a);fs.readFile(a,f?void 0:"utf8",(g,h)=>{g?b(g):c(f?h.buffer:h)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=d);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof C||a.context instanceof C))throw a;});r=(a,c)=>
{process.exitCode=a;throw c;}}else if(k||l)l?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),t=t.startsWith("blob:")?"":t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1),u=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},l&&(w=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),v=(a,c,b)=>{var f=new XMLHttpRequest;f.open("GET",a,
!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):b()};f.onerror=b;f.send(null)};var aa=d.print||console.log.bind(console),D=d.printErr||console.error.bind(console);Object.assign(d,q);q=null;d.quit&&(r=d.quit);var E;d.wasmBinary&&(E=d.wasmBinary);var F,G=!1,H,I,ba,J,ca,da,ea=[],fa=[],ha=[],ia=[];function ja(){var a=d.preRun.shift();ea.unshift(a)}var K=0,L=null,M=null;
function ka(a){d.onAbort?.(a);a="Aborted("+a+")";D(a);G=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var la=a=>a.startsWith("data:application/octet-stream;base64,"),B=a=>a.startsWith("file://"),N;function ma(a){if(a==N&&E)return new Uint8Array(E);if(w)return w(a);throw"both async and sync fetching of the wasm failed";}
function na(a){if(!E&&(k||l)){if("function"==typeof fetch&&!B(a))return fetch(a,{credentials:"same-origin"}).then(c=>{if(!c.ok)throw`failed to load wasm binary file at '${a}'`;return c.arrayBuffer()}).catch(()=>ma(a));if(v)return new Promise((c,b)=>{v(a,f=>c(new Uint8Array(f)),b)})}return Promise.resolve().then(()=>ma(a))}function oa(a,c,b){return na(a).then(f=>WebAssembly.instantiate(f,c)).then(b,f=>{D(`failed to asynchronously prepare wasm: ${f}`);ka(f)})}
function pa(a,c){var b=N;E||"function"!=typeof WebAssembly.instantiateStreaming||la(b)||B(b)||n||"function"!=typeof fetch?oa(b,a,c):fetch(b,{credentials:"same-origin"}).then(f=>WebAssembly.instantiateStreaming(f,a).then(c,function(g){D(`wasm streaming compile failed: ${g}`);D("falling back to ArrayBuffer instantiation");return oa(b,a,c)}))}
var ua={19976:a=>{a=a?O(H,a):"";const c=document.createElement("input");c.id=a;c.type="text";c.style.position="absolute";c.style["font-family"]="Ubuntu";c.style.display="none";c.style["border-width"]="0px";c.style.background="transparent";c.style.border="none";c.style.outline="none";c.style["padding-left"]="2px";document.body.appendChild(c)},20395:a=>{a=a?O(H,a):"";document.getElementById(a).style.display="block"},20504:a=>{a=a?O(H,a):"";a=document.getElementById(a);a.style.display="none";a.style.width=
a.style.height="0px"},20658:(a,c,b,f,g)=>{a=a?O(H,a):"";a=document.getElementById(a);a.style.left=(c-f/2)/devicePixelRatio+"px";a.style.top=(b-g/2)/devicePixelRatio+"px";a.style.width=f/devicePixelRatio+"px";a.style.height=g/devicePixelRatio+"px";a.style["font-size"]=g/devicePixelRatio*.8+"px"},21015:(a,c,b)=>{a=a?O(H,a):"";a=document.getElementById(a);a=(new TextEncoder).encode(a.value);b=b>a.length?a.length:b;a=a.slice(0,b);H.set(a,c);H[c+b]=0},21257:(a,c)=>{a=a?O(H,a):"";document.getElementById(a).value=
c?O(H,c):""},21367:a=>{let c=document.createElement("textarea");c.style.position="fixed";c.style.top=0;c.style.left=0;c.style.width="2em";c.style.height="2em";c.style.margin=0;c.style.padding=0;c.style.border="none";c.style.outline="none";c.style.boxShadow="none";c.style.background="transparent";c.value=a?O(H,a):"";document.body.appendChild(c);c.focus();c.select();try{document.execCommand("copy")||console.log("execCommand copy failed")}catch(b){}document.body.removeChild(c)},21937:()=>+/iPhone|iPad|iPod|Android/i.test(navigator.userAgent),
22008:a=>{try{window.open(a?O(H,a):"","_blank").focus()}catch(c){}},22083:(a,c,b)=>{a=a?O(H,a):"";c=(new TextDecoder).decode(H.subarray(c,c+b-1));window.localStorage[a]=c},22231:(a,c)=>{a=a?O(H,a):"";a=window.localStorage[a];if(!a)return 0;H.set((new TextEncoder).encode(a),c);return a.length},22401:a=>{document.getElementById(a?O(H,a):"").value=prompt()},22490:a=>{function c(b){null==window.start&&(window.start=b+1);const f=Math.min(.5,(b-window.start)/1E3);window.start=b;d.canvas.width=innerWidth*
devicePixelRatio;d.canvas.height=innerHeight*devicePixelRatio;qa(a,f,d.canvas.width,d.canvas.height,devicePixelRatio);requestAnimationFrame(c)}d.canvas=document.createElement("canvas");d.canvas.id="canvas";d.canvas.oncontextmenu=function(){return!1};window.onbeforeunload=function(){return"Are you sure?"};document.body.appendChild(d.canvas);d.v=[d.canvas.getContext("2d")];d.A=Array(256).fill(0).map(function(b,f){return f});window.onkeydown=function(b){P(a,1,b.which,b.key?(!b.ctrlKey&&!b.metaKey&&1==
b.key.length)*b.key.charCodeAt():0)};window.onkeyup=function(b){P(a,0,b.which,b.key?(!b.ctrlKey&&!b.metaKey&&1==b.key.length)*b.key.charCodeAt():0)};window.addEventListener("mousedown",async function(b){Q(a,b.clientX*devicePixelRatio,b.clientY*devicePixelRatio,1,+!!b.button)});window.addEventListener("mousemove",async function(b){Q(a,b.clientX*devicePixelRatio,b.clientY*devicePixelRatio,2,+!!b.button)});window.addEventListener("mouseup",async function(b){Q(a,b.clientX*devicePixelRatio,b.clientY*devicePixelRatio,
0,+!!b.button)});window.addEventListener("touchstart",function(b){b.preventDefault();b.stopPropagation();if(b.changedTouches.length){var f=b.changedTouches[0];Q(a,f.clientX*devicePixelRatio,f.clientY*devicePixelRatio,1,0);for(const g of b.changedTouches)R(a,g.clientX*devicePixelRatio,g.clientY*devicePixelRatio,1,g.identifier)}},{passive:!1});window.addEventListener("touchmove",function(b){b.preventDefault();b.stopPropagation();if(b.changedTouches.length){var f=b.changedTouches[0];Q(a,f.clientX*devicePixelRatio,
f.clientY*devicePixelRatio,2,0);for(const g of b.changedTouches)R(a,g.clientX*devicePixelRatio,g.clientY*devicePixelRatio,1,g.identifier)}},{passive:!1});window.addEventListener("touchend",function(b){b.preventDefault();b.stopPropagation();if(b.changedTouches.length){var f=b.changedTouches[0];Q(a,f.clientX*devicePixelRatio,f.clientY*devicePixelRatio,0,0);for(const g of b.changedTouches)R(a,g.clientX*devicePixelRatio,g.clientY*devicePixelRatio,0,g.identifier)}},{passive:!1});window.addEventListener("wheel",
async function({deltaY:b}){ra(a,b)});document.body.addEventListener("paste",async function(b){b=(new TextEncoder).encode(b.clipboardData.getData("text/plain"));const f=S(b.length+1);H.set(b,f);H[f+b.length]=0;sa(a,f)});d.B=function(){if(d.A.length){const b=d.A.shift();if(0==b)return 0;d.v[b]=(new OffscreenCanvas(1,1)).getContext("2d");return b}throw Error("Out of Contexts: Can be fixed by allowing more contexts");};d.C=function(b){if(0==b)throw Error("Tried to delete the main context");d.v[b]=null;
d.A.push(b)};requestAnimationFrame(c)},26376:(a,c,b)=>{let f=c?O(H,c):"";d.socket&&2>d.socket.readyState&&d.socket.close();(function(){let g=d.socket=new WebSocket(f);g.binaryType="arraybuffer";g.onopen=function(){U(a,0,0,0)};g.onclose=function(h){U(a,1,0,h.code)};g.onmessage=function(h){H.set(new Uint8Array(h.data),b);U(a,2,b,(new Uint8Array(h.data)).length)}})()},26916:(a,c)=>{d.socket.send(H.subarray(a,a+c))},26970:(a,c)=>{d.socket.send(H.subarray(a,a+c))},27024:(a,c,b)=>{fetch((a?O(H,a):"")+"user_get_password/"+
(c?O(H,c):"")).then(f=>f.text()).then(f=>{const g=S(f.length+1);H.set((new TextEncoder).encode(f),g);H[g+f.length]=0;ta(g,b);V(g)})},27291:(a,c,b)=>{a=a?O(H,a):"";let f=c?O(H,c):"",g=b?O(H,b):"",h;fetch("https://identity.api.rivet.gg/v1/game-links",{method:"POST",body:"{}",headers:{Authorization:"Bearer "+a}}).then(e=>e.json()).then(e=>{function p(y){y.then(m=>m.json()).then(m=>{if("incomplete"===m.status){console.log("<not linked yet, checking again>");let z=fetch("https://identity.api.rivet.gg/v1/game-links?identity_link_token="+
e.identity_link_token+"&watch_index="+m.watch.index);p(z)}else"cancelled"===m.status?console.log("<cancelled linking>"):"complete"===m.status&&fetch(f+"user_get_password/"+m.new_identity.identity_token).then(z=>z.text()).then(z=>{fetch(f+"account_link/"+m.current_identity.identity_id+"/"+g+"/"+m.new_identity.identity.identity_id+"/"+z).then(T=>T.text()).then(T=>{"success"!==T?alert("Linking failed: please try again\nattempted to link "+m.current_identity.identity_id+" and "+m.new_identity.identity.identity_id+
"\nPlease screenshot this and send to devs"):(h.close(),window.localStorage.old_account_uuid=m.current_identity.identity_id,window.localStorage.DO_NOT_SHARE_old_rivet_account_token=window.localStorage.DO_NOT_SHARE_rivet_account_token,window.localStorage.DO_NOT_SHARE_rivet_account_token=m.new_identity.identity_token,location.reload(!1))})})})}h=window.open(e.identity_link_url,"","width=600,height=600");let A=fetch("https://identity.api.rivet.gg/v1/game-links?identity_link_token="+e.identity_link_token);
p(A)})},29102:()=>d.B(),29130:(a,c,b)=>{d.v[a].canvas.width=c;d.v[a].canvas.height=b},29205:a=>{a=a?O(H,a):"";d.v[0].font="1px Ubuntu";return d.v[0].measureText(a).width},29325:(a,c,b)=>{for(let g=0;g<c;++g){const h=I[a+2>>1];var f=I[a+4>>1];const e=ca.subarray(a+8>>2,a+32>>2),p=J[a+32>>2];switch(H[a]){case 0:d.v[h].fillStyle="rgba("+e[0]+","+e[1]+","+e[2]+","+e[3]+")";break;case 1:d.v[h].strokeStyle="rgba("+e[0]+","+e[1]+","+e[2]+","+e[3]+")";break;case 2:d.v[h].lineWidth=e[0];break;case 3:d.v[h].font=
e[0]+"px Ubuntu";break;case 4:d.v[h].globalAlpha=e[0];break;case 5:0==e[0]?d.v[h].lineCap="butt":1==e[0]?d.v[h].lineCap="round":2==e[0]&&(d.v[h].lineCap="square");break;case 6:0==e[0]?d.v[h].lineJoin="bevel":1==e[0]?d.v[h].lineJoin="round":2==e[0]&&(d.v[h].lineJoin="miter");break;case 7:0==e[0]?d.v[h].textAlign="left":1==e[0]?d.v[h].textAlign="center":2==e[0]&&(d.v[h].textAlign="right");break;case 8:0==e[0]?d.v[h].textBaseline="top":1==e[0]?d.v[h].textBaseline="middle":2==e[0]&&(d.v[h].textBaseline=
"bottom");break;case 9:d.v[h].setTransform(e[0],e[1],e[3],e[4],e[2],e[5]);break;case 10:d.v[h].save();break;case 11:d.v[h].restore();break;case 12:d.v[h].beginPath();break;case 13:d.v[h].moveTo(e[0],e[1]);break;case 14:d.v[h].lineTo(e[0],e[1]);break;case 15:d.v[h].quadraticCurveTo(e[0],e[1],e[2],e[3]);break;case 16:d.v[h].bezierCurveTo(e[0],e[1],e[2],e[3],e[4],e[5]);break;case 17:d.v[h].arc(e[0],e[1],e[2],e[3],e[4],e[5]);break;case 18:d.v[h].ellipse(e[0],e[1],e[2],e[3],0,6.283185307179586,0);break;
case 19:d.v[h].rect(e[0],e[1],e[2],e[3]);break;case 20:d.v[h].drawImage(d.v[f].canvas,e[0],e[1],e[2],e[3],e[4],e[5],e[2],e[3]);break;case 21:d.v[h].fillRect(e[0],e[1],e[2],e[3]);break;case 22:d.v[h].strokeRect(e[0],e[1],e[2],e[3]);break;case 23:d.v[h].fill();break;case 24:d.v[h].stroke();break;case 25:d.v[h].clip();break;case 26:d.v[h].clip("evenodd");break;case 27:f=p?O(H,p):"";d.v[h].fillText(f,e[0],e[1]);V(p);break;case 28:f=p?O(H,p):"",d.v[h].strokeText(f,e[0],e[1]),V(p)}a+=b}}};
function C(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var W=a=>{for(;0<a.length;)a.shift()(d)},va=d.noExitRuntime||!0,X=[],wa=(a,c)=>{X.length=0;for(var b;b=H[a++];){var f=105!=b;f&=112!=b;c+=f&&c%8?4:0;X.push(112==b?J[c>>2]:105==b?ba[c>>2]:da[c>>3]);c+=f?8:4}return X},xa=[null,[],[]],ya="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,O=(a,c)=>{for(var b=c+NaN,f=c;a[f]&&!(f>=b);)++f;if(16<f-c&&a.buffer&&ya)return ya.decode(a.subarray(c,f));for(b="";c<f;){var g=a[c++];if(g&128){var h=a[c++]&63;if(192==(g&224))b+=String.fromCharCode((g&
31)<<6|h);else{var e=a[c++]&63;g=224==(g&240)?(g&15)<<12|h<<6|e:(g&7)<<18|h<<12|e<<6|a[c++]&63;65536>g?b+=String.fromCharCode(g):(g-=65536,b+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else b+=String.fromCharCode(g)}return b},za={e:(a,c,b)=>H.copyWithin(a,c,c+b),b:(a,c,b)=>{c=wa(c,b);return ua[a](...c)},a:(a,c,b)=>{c=wa(c,b);return ua[a](...c)},f:()=>Date.now(),c:()=>{ka("OOM")},d:(a,c,b,f)=>{for(var g=0,h=0;h<b;h++){var e=J[c>>2],p=J[c+4>>2];c+=8;for(var A=0;A<p;A++){var y=H[e+A],m=xa[a];0===
y||10===y?((1===a?aa:D)(O(m,0)),m.length=0):m.push(y)}g+=p}J[f>>2]=g;return 0}},Y=function(){function a(b){Y=b.exports;F=Y.g;b=F.buffer;d.HEAP8=new Int8Array(b);d.HEAP16=new Int16Array(b);d.HEAPU8=H=new Uint8Array(b);d.HEAPU16=I=new Uint16Array(b);d.HEAP32=ba=new Int32Array(b);d.HEAPU32=J=new Uint32Array(b);d.HEAPF32=ca=new Float32Array(b);d.HEAPF64=da=new Float64Array(b);fa.unshift(Y.h);K--;d.monitorRunDependencies?.(K);0==K&&(null!==L&&(clearInterval(L),L=null),M&&(b=M,M=null,b()));return Y}var c=
{a:za};K++;d.monitorRunDependencies?.(K);if(d.instantiateWasm)try{return d.instantiateWasm(c,a)}catch(b){return D(`Module.instantiateWasm callback failed with error: ${b}`),!1}N||=la("rrolf-client.wasm")?"rrolf-client.wasm":d.locateFile?d.locateFile("rrolf-client.wasm",t):t+"rrolf-client.wasm";pa(c,function(b){a(b.instance)});return{}}(),S=d._malloc=a=>(S=d._malloc=Y.i)(a),V=d._free=a=>(V=d._free=Y.j)(a),ta=d._rr_api_on_get_password=(a,c)=>(ta=d._rr_api_on_get_password=Y.k)(a,c);
d._rr_rivet_on_log_in=(a,c,b,f,g,h,e)=>(d._rr_rivet_on_log_in=Y.l)(a,c,b,f,g,h,e);d._rr_rivet_lobby_on_find=(a,c,b,f)=>(d._rr_rivet_lobby_on_find=Y.m)(a,c,b,f);
var P=d._rr_key_event=(a,c,b,f)=>(P=d._rr_key_event=Y.n)(a,c,b,f),Q=d._rr_mouse_event=(a,c,b,f,g)=>(Q=d._rr_mouse_event=Y.o)(a,c,b,f,g),R=d._rr_touch_event=(a,c,b,f,g)=>(R=d._rr_touch_event=Y.p)(a,c,b,f,g),ra=d._rr_wheel_event=(a,c)=>(ra=d._rr_wheel_event=Y.q)(a,c),sa=d._rr_paste_event=(a,c)=>(sa=d._rr_paste_event=Y.r)(a,c),qa=d._rr_renderer_main_loop=(a,c,b,f,g)=>(qa=d._rr_renderer_main_loop=Y.s)(a,c,b,f,g),Aa=d._main=(a,c)=>(Aa=d._main=Y.t)(a,c),U=d._rr_on_socket_event_emscripten=(a,c,b,f,g)=>(U=
d._rr_on_socket_event_emscripten=Y.u)(a,c,b,f,g),Z;M=function Ba(){Z||Ca();Z||(M=Ba)};
function Ca(){function a(){if(!Z&&(Z=!0,d.calledRun=!0,!G)){W(fa);W(ha);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Da){var c=Aa;try{var b=c(0,0);va||(d.onExit?.(b),G=!0);r(b,new C(b))}catch(f){f instanceof C||"unwind"==f||r(1,f)}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)c=d.postRun.shift(),ia.unshift(c);W(ia)}}if(!(0<K)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)ja();W(ea);0<K||(d.setStatus?(d.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Da=!0;d.noInitialRun&&(Da=!1);Ca();
